README.md

For those who want to use Closure Compiler to compile and minify their Rollup bundles.

Add Closure Compiler Plugin

---

README.md

The rollup-plugin-node-builtins link is pointing to an empty repo. I think it's meant to point to @calvinmetcalf's one.

Fix link to rollup-plugin-node-builtins

---

README.md

This addition lists `lit-html` as one of the options in the templating section. I chose this section because I think it fits better than others, but arguments could be made that `lit-html` is not strictly a templating library, and this plugin modifies the code output so that the HTML is converted into a template function for use with other `lit-html` tooling (like `render`) or `lit-element`.
I'm happy to move the category this is in, but I think most people will perceive `lit-html` as being a templating tool.
As implied by the name, `rollup-plugin-lit-html` allows an application to separate their `lit-html` template (essentially just raw HTML with template string interpolation) from the rest of their JavaScript. It's not for everyone, as many people like …

Add `lit-html`

---

README.md

The removed plugin both states it is unmaintained, and actively points to the official one (the remaining Vue plugin) as the preferred alternative.
The official one supports all versions of Vue (including v2), so the wording on the links/descriptions was a bit poor here anyway.

Remove unmaintained plugin

---

README.md

This plugin will inject the application's version number and/or the build date into built js, html, and css files. This is extremely helpful for debugging especially if multiple versions of static files are uploaded to a web server/cdn. It also helps with logging as the current version and/or build date can be dynamically sent to log services.  
[Github repo](https://github.com/djhouseknecht/rollup-plugin-version-injector)

Added version-injector to the list

---

README.md

https://github.com/mentaljam/rollup-plugin-zip
Plugin to zip up emitted files. It was inspired by the zip-webpack-plugin.
This plugin doesn't list the output directory but gets entries from the resulting bundle.

Add rollup-plugin-zip

---

README.md

[rollup-plugin-by-output](https://github.com/wmzy/rollup-plugin-by-output) support apply plugins according to special output option.
Example, apply `terser` for only min output files, with this plugin we need not two or more configs.

add rollup-plugin-by-output

---

README.md

https://github.com/pearofducks/rollup-plugin-dev
This plugin is intended to act as an _alternative_ to (not compete with) [rollup-plugin-serve](https://github.com/thgh/rollup-plugin-serve).
To ensure users can find the right plugin for their needs, I've linked to _serve_ early on in the README, and suggested it for users who only need to serve static files.
This plugin, compared to _serve_ offers the following:
- based on Koa, so fully extensible by the user
- detailed logging of requests (see screenshot in repo's README)
- full proxy support
- support for a basepath in the URL
- will automatically turn itself off (with a notification) for production builds

Add rollup-plugin-dev

---

README.md

https://github.com/juliendargelos/rollup-plugin-emit-ejs
This plugin allows for generating files from ejs templates. It includes a basic layout system and provides `javascripts` and `stylesheets` helper variables to link bundled files to html pages.

Add rollup-plugin-emit-ejs

---

README.md

https://github.com/surma/rollup-plugin-off-main-thread
Use Rollup with workers and ES6 modules _today_. loadz0r has been replaced by off-main-thread.

add: rollup-plugin-off-main-thread

---

README.md

https://github.com/NotWoods/rollup-plugin-consts
Allows for importing constants at built time. It serves a similar purpose to [@rollup/plugin-replace](https://github.com/rollup/plugins/tree/master/packages/replace), but lets constants be imported as modules instead of being string replacements.

add: rollup-plugin-consts

---

README.md

https://github.com/weizhenye/rollup-plugin-bundle-scss
It bundles all SCSS imports into one SCSS file. It's useful when writing UI components with SCSS and providing one SCSS file to users for theming.

add: rollup-plugin-bundle-scss

---

README.md

- [ x] I have read, and re-read the [Contributing Guidelines](https://github.com/rollup/awesome/blob/master/.github/CONTRIBUTING.md)
- [x ] I have searched to ensure the suggested item doesn't exist on this list
- [x ] This PR contains only one item
https://github.com/shuizhongyueming/rollup-plugin-output-manifest
This plugin can generate a manifest file for all chunk. So we can use this manifest to dynamically load chunk with dynamic content hash in the output file name.

Add rollup-plugin-output-manifest

---

README.md

https://github.com/Vehmloewff/rollup-plugin-command
This PR aims at adding `rollup-plugin-command` to the awesome list.
This plugin is very similar to [`rollup-plugin-execute`](https://github.com/audinue/rollup-plugin-execute), but has a couple distinguishing features.
- This plugin allows both shell commands to be run _and_ functions to be called.  `rollup-plugin-execute` only supports shell commands.
- This plugin has, unlike `rollup-plugin-execute`, an `exitOnFail` option.  This is very important if you are using this plugin to run tests.

Add a link to rollup-plugin-command

---

README.md

https://github.com/Anidetrix/rollup-plugin-styles
Universal plugin for styles: PostCSS, Sass, Less, Stylus and more.
Differs from rollup-plugin-postcss:
* Written completely in TypeScript
* Up-to-date CSS Modules implementation
* Built-in @import handler
* Built-in assets handler
* Code splitting support
* Ability to emit pure CSS for other plugins
* Correct multiple instance support with check for already processed files
* Support for implementation and fibers forcing for Sass
* Support for partials and ~ in Less import statements
* Sourcemaps include source content
* Proper sourcemap generation for all loaders
* Correct inline sourcemaps
* Correct relative source paths in extracted sourcemaps
* Extracts sourcemaps from loaded files
* More smaller things …

Add rollup-plugin-styles

---

README.md

Hi!
It seems the link to the Babel plugin should refer to the actual location of the package.

Fix link to Babel plugin

---

README.md

`rollup-plugin-babel-minify` has been deprecated (see https://github.com/Comandeer/rollup-plugin-babel-minify), with the suggested replacement being `rollup-plugin-terser` (already listed here). Removing it accordingly.
N/A
N/A

Remove babel-minify (deprecated)

---

README.md

https://github.com/vikerman/rollup-plugin-hoist-import-deps
When a module is dynamically imported, it's static imports in turn are loaded after the dynamic import is downloaded and parsed. This causes a delay when doing dynamic imports especially with slow/high latency connections. This plugin changes the dynamic import call site to also add(hoist) the static imports of the module being loaded so that the dynamically imported module and it's dependencies are loaded in parallel instead of in two steps.

add: hoist-import-deps

---

README.md

https://github.com/snowpackjs/rollup-plugin-polyfill-node
As a follow-up to https://github.com/rollup/awesome/pull/92, it turns out that this package is the most up to date choice for including Node builtins into Rollup bundles.
Also related: https://github.com/rollup/rollup/pull/4190

Add polyfill-node

---

README.md

https://github.com/docd27/rollup-plugin-glsl-optimize
Import and optimize GLSL shaders as compressed strings. Supports [glslify](https://github.com/glslify/glslify).
In addition to simply importing GLSL shaders as strings as these existing plugins do, this also provides:
- Semantic validation and macro preprocessing at bundle time (using [glslangValidator](https://github.com/KhronosGroup/glslang))
- Optimization (using [spirv-opt](https://github.com/KhronosGroup/SPIRV-Tools))

Add rollup-plugin-glsl-optimize

---

README.md

Adds build statistics plugin, moves dev plugin so that the list is alphabetically sorted
https://github.com/nemwiz/build-statistics-plugin
A plugin that keeps a continuous log of build time and helps to monitor team productivity.
I wrote a blog post on my motivation to build this plugin.
https://www.ninkovic.dev/blog/2021/how-to-acquire-more-time-for-technical-tasks

Adds build statistics plugin

---

README.md

https://github.com/swiing/rollup-plugin-import-assertions
This plugin adds support for [TC39 import assertions](https://github.com/tc39/proposal-import-assertions). This is currently a stage 3 proposal.
Import assertions allow importing assets with the following syntax;
```js
import json from "./foo.json" assert { type: "json" };
import style from "./style.css" assert { type: "css" };
```
The latter is especially useful with custom elements.

Add import-assertions plugin

---

README.md

https://github.com/soufyakoub/rollup-plugin-external-assets
Imports to assets whose resolved id matches the provided pattern(s) are made external, but the assets themselves are emitted in the final output, and the imports are correctly updated to reference the target location of those assets.
This is useful for package creators. For example, a reusable react component that imports assets and the author wants to let the user choose how to bundle them.
`smart-asset` does the same thing with the "copy" mode, but from my experiments, since the provided assets target directory has to be relative to the output file, it only works as expected when the output is a single chunk.
`rebase` does the same thing too, but I checked its source, and it seems that it's using …

add external-assets

---

README.md

https://github.com/m00nbyte/rollup-plugin-strip-prop-types
Removes propTypes, defaultProps, and prop-types imports, with TypeScript support and custom import paths.

add rollup-plugin-strip-prop-types

---

README.md

[https://github.com/SLTKA/rollup-plugin-keep-css-imports](https://github.com/SLTKA/rollup-plugin-keep-css-imports)
`keep-css-imports` allows to maintain the original structure of style imports (CSS, SCSS, or SASS) without altering them during the bundling process. It will be helpful for building a components library and want to keep all CSS module imports untouched so consumer decide how to bundle or tree shake them.
If it meets SASS or SCSS import it will compile it and output as a single imported CSS file in `dist`. Plugin can be configured to maintain component folder structure or produce flattened output.
Rollup and Webpack based consumers can easily ignore the produced CSS file if component imported them was not used.
This is an alternative to …

Add keep-css-imports plugin

---

README.md

https://github.com/Anidetrix/rollup-plugin-styles
This package is unmaintained and only supports rollup 2.x. There were attempts to contribute new version support, but no response: https://github.com/Anidetrix/rollup-plugin-styles/pull/225
At this point it would be better not to confuse people by suggesting an outdated package

remove rollup-plugin-styles from the list
