- README.md
This adds Nollup which otherwise users might not be able to find. Open to including it in another section as appropriate. I haven't personally tested this so can't necessarily vouch for stability but I really like the approach in principle.
> Add nollup

- README.md
Added the reference to the [less-modules](https://github.com/katrotz/rollup-plugin-less-modules) rollup plugin.
> Adds less-modules reference

- README.md
> Add iife plugin

- README.md
> add rollup-plugin-banner

- README.md
This is an update to an existing plugin. glslify/rollup-plugin-glslify#3
> Update glslify, now the official plugin for glslify

- README.md
This plugin adds support for a different file format, so move it to that section.
This is a correction, not an addition.
> Move dsv to the correct category

- README.md
`rollup-plugin-imagemin` uses imagemin to optimize image assets. It functions like most any other abstraction of imagemin, and offers many of the same features.
> Add rollup-plugin-imagemin

- README.md
> rollup-plugin-bundle-html

- README.md
[rollup-plugin-app-utils](https://github.com/Autodesk/rollup-plugin-app-utils) provides common rollup build utils for i18n, prepare & clean directories, copy assets & html injects. These are common tasks for project build.
It contains excellent i18n building mechanism and synchronous assets copying and directory preparation utils. As part of our application development we used this and it works great.
> Add rollup-plugin-app-utils

- README.md
rollup-plugin-smart-asset plugin
> Add rollup-plugin-smart-asset

- README.md
rollup-plugin-replace points to old repository. Updating to new one.
> Update rollup-plugin-replace link

- README.md
> cpy repo has been moved

- README.md
https://github.com/wessberg/rollup-plugin-ts
This plugin is, in my opinion, the best for using TypeScript with rollup, as it gives the option to transpile it using Babel, while complying with Browserslist (both these things are optional), as well as also bundling the type files.
> Add @wessberg/rollup-plugin-ts

- README.md
Update the remaining URLs to the monorepo (except Babel which is not migrated).
> Update references to official plugins

- README.md
https://github.com/daankauwenberg/rollup-plugin-mjml
It provides a parser to export html e-mailtemplates build with MJML
> Add rollup-plugin-mjml

- README.md
The repo has been "archived" and it hasn't been updated in a few years.
> Remove `stub` repo

- README.md
https://github.com/adamzerella/rollup-plugin-manifest-json
Allows users to load and modify a `manifest.json` into the rollup build, given a template `manifest.json` file.
> Add "rollup-plugin-manifest-json" to the list.

- README.md
https://github.com/surma/rollup-plugin-off-main-thread
This plugins allows you to use AMD and adds support to use ES6 modules inside workers.
__This plugin has not been written by me__.  The author is @surma, a well known developer advocate from Google.
I've personally got a lot of value out of this plugin –  that's why I'm suggesting it to the list.
> Add OMT plugin by Surma

- README.md
https://github.com/kpulkit29/rollup-plugin-concatfiles
Plugin to concatenate files/content to the generated output. This plugin would enable the user to concatenate files to the output or any other file in general.
> Add concat files plugin to rollup awesome plugins (output list)

- README.md
https://github.com/surma/rollup-plugin-off-main-thread
The plugin at the URL:
https://github.com/surma/rollup-plugin-off-main-thread
appeared twice in the list with different names:
- OMT
- off-main-thread
I have deleted the most recent entry with the least descriptive name.
> chore: remove duplicated entry

- README.md
https://github.com/darionco/rollup-plugin-web-worker-loader
After over a year of life, the plugin has reached maturity and is now at version > 1.0.0.
Here's a list of features:
- Package for web, NodeJS or automatically detect the platform at runtime.
- Supports ES6 modules.
- Code-split the result or inline it in Base64
- Supports source maps.
- Supports unicode through UTF16
There's a similar plugin in the list already:
https://github.com/surma/rollup-plugin-off-main-thread
(which is duplicated, I'll submit a separate PR to delete one of the entries)  
The original version of [OMT](https://github.com/surma/rollup-plugin-off-main-thread), [loadz0r](https://github.com/surma/rollup-plugin-loadz0r), and …
> add: web-worker-loader

- README.md
> Change unassert URL from gitlab to github

- README.md
https://github.com/vinicius73/rollup-plugin-pika-resolver
https://www.npmjs.com/package/@vinicius73/rollup-plugin-skypack-resolver
Generate the bundle of your project using [Skypack CDN](https://skypack.dev/) for external dependencies.
> add skypack-resolver

- README.md
https://github.com/chrisprice/grunt-rollup
This is a Grunt plugin to run Rollup.
> Add grunt-rollup

- README.md
https://github.com/rafgraph/rollpkg
Rollpkg is a convention over configuration way to build packages with Rollup and TypeScript. It creates `esm`, `cjs` and `umd` builds for development and production, and fully supports tree shaking.
> Add rollpkg

- README.md
https://github.com/mprt-org/rollup-plugin-incremental
A Rollup plugin which makes your (development) builds much faster, by recompiling only changed modules.
> Add rollup-plugin-incremental

- README.md
<https://github.com/cmorten/deno-rollup>
`deno-rollup` ports Rollup so it can be used within Deno scripts to bundle modules.
> Add deno-rollup

- README.md
https://github.com/exuanbo/rollup-plugin-esbuild-transform
Transform with [esbuild](https://github.com/evanw/esbuild).
> Add esbuild-transform

- README.md
https://github.com/juliendargelos/rollup-plugin-html-minifier
This plugin minifies html files in rollup bundle with [html-minifier](https://github.com/kangax/html-minifier).
> Add rollup-plugin-html-minifier

- README.md
https://github.com/victornpb/rollup-plugin-baked-env
This plugin allow you to use environment variables inside your code by importing process.env as a faux module. The environment variable will be baked into your bundle at compile time. It leverages rollup _tree shakable modules_ to only include variables being used. Compilation fails if there are imports to unset variables.
```js
import { NODE_ENV, FOO, BAR } from 'process.env';
console.log(FOO, BAR);
if (NODE_ENV === 'production') {
// code
}
```
> rollup-plugin-baked-env

- README.md
https://github.com/YanceyOfficial/rollup-plugin-toml
A Rollup plugin which Converts TOML files to ES6 modules.
> feat: add rollup-plugin-toml

- README.md
https://github.com/TrickyPi/rollup-copy-smartly
smartly copy files if they are changed, deleted or created.
> add copy-smartly plugin

- README.md
https://github.com/petlack/rollup-plugin-jsonlines
Import .jsonl ([JSON Lines](https://jsonlines.org/)) files as JSON arrays.
_`fruits.jsonl`_
```json
{ "type": "apples", "count": 7 }
{ "type": "pears", "count": 4 }
{ "type": "bananas", "count": 5 }
```
_`index.js`_
```js
import fruits from './fruits.jsonl';
console.log(fruits);
```
_`log`_
```json
[
{ "type": "apples", "count": 7 },
{ "type": "pears", "count": 4 },
{ "type": "bananas", "count": 5 }
]
```
> add: jsonlines plugin

- README.md
Adds `rollup-plugin-styler` a more up-to-date and maintained fork of `rollup-plugin-styles`.
See https://github.com/plumelo/rollup-plugin-styler
https://github.com/plumelo/rollup-plugin-styler
Adds rollup-plugin-styler a more up-to-date and maintained fork of rollup-plugin-styles. See https://github.com/plumelo/rollup-plugin-styler
> add: styler css plugin

- README.md
https://github.com/dmnsgn/rollup-plugin-no-op
Replace imported modules with an empty object (`export default {}`).
> docs: add rollup-plugin-no-op

- README.md
[https://github.com/rollup/plugins/tree/master/packages/dynamic-import-vars](https://github.com/rollup/plugins/tree/master/packages/dynamic-import-vars)
Add plugin [dynamic-import-vars](https://github.com/rollup/plugins/tree/master/packages/dynamic-import-vars) into list, which support resolving dynamic imports that contain variables, maintained by rollup official.
> add dynamic-import-vars

- README.md
https://github.com/gushogg-blake/rollup-plugin-spincheck
Instrument `while` and `do-while` blocks to debug infinite loops and prevent freezing.
This plugin implements a shorthand for adding a max iterations check to loops to ensure that they don't freeze if there's a bug in the algorithm, for example when using complex logic to find a node in a tree.
If an annotated loop performs more than the max iterations, an error is thrown and useful debug info is logged to the console. If dev tools is open, it can be configured to step straight into the debugger.
Example:
```typescript
function smallestAtCharCursor(node, cursor) {
if (!node.containsCharCursor(cursor)) {
return null;
}
let smallestNode = node;
let {children} = smallestNode;
let startIndex = 0;
let …
```
> Add spincheck - instrument while/do-while to debug infinite loops

- README.md
https://github.com/jleeson/rollup-plugin-import-css
import-css is a plugin for importing CSS in JavaScript in a variety of ways and doing additional processing of the css files.
> If you submit a project that is similar to an existing project in the list, please explain how you feel yours is better.
Compared to other plugins that enable importing css files, `import-css` enables importing the css to be extracted to a bundle, importing as a string, and importing as a native css module, all in the same project without changes in configuration. This plugin also supports basic minification as well as additional options for further transforms. `import-css` also supports preserveModules and will optionally preserve the css imports in the bundle for cases where the …
> add: `rollup-plugin-import-css` - a plugin to import CSS into JavaScript

- README.md
https://github.com/jacobbogers/rollup-plugin-jsx-remove-attributes
This plugin removes  `data-testid` (this is configurable) attribute from react production builds, previous art used babel (slow).
> added output plugin remove jsx attribute
